### ISSUE TITLE
Fetch errors preventing building of container

### ISSUE THREAD

**Issue by yanickpouliot** [tiagoantao/bioinf-python#4]
Dear Tiago, when trying to instantiate this container per below (slightly different from your book), I get the error listed below. Can this be addressed?

command: 

sudo docker build -t bio https://raw.githubusercontent.com/tiagoantao/bioinf-python/master/docker/2/Dockerfile

erors:

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/universe/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/main/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/main/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/restricted/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/universe/source/Sources  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.24 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by tiagoantao** [comment]
I was expecting for this to happen, as things change very fast in this field.
I will have a look at this today and audit the situation. And update the repository if necessary

**Comment by tiagoantao** [comment]
@yanickpouliot Many thanks for this. The base Ubuntu version was utopic, which is not supported anymore. I have updated the scripts to wily. As soon as the images are built and working, I will put the information here.

Thanks!

**Comment by tiagoantao** [comment]
@yanickpouliot I think I have solved the problem, but there is now an even easier way:

just do
docker pull tiagoantao/bioinf-python
[Python 3]
or
docker pull tiagoantao/bioinf-python-legacy

Please tell me if the problem is sorted out, or not...

Thanks
