### ISSUE TITLE
1000 genomes dataset address now a dead link

### ISSUE THREAD

**Issue by juefish** [tiagoantao/bioinf-python#5]
Address you have for 1000 genomes dataset in chapter doesn't work. Dead link I think. Can you a provide an archived file or direct to existing location of an updated file?

Cheers,
Nate

**Comment by tiagoantao** [comment]
Could you tell me precisely which dataset is problematic? I have corrected the links here some time ago and the ones I tested are OK. Please point me to a precise case and I will correct it.

Thanks

**Comment by juefish** [comment]
The sequence.index file you reference in chapter 1 has moved. I think it is here now:

ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp//data_collections/1000_genomes_project/1000genomes.sequence.index

But I'm not sure if it's a work-able file for your example or not.

**Comment by tiagoantao** [comment]
Thanks for the report. I have now corrected this.

For future reference, the FTP file is:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/historical_data/former_toplevel/sequence.index
