### ISSUE TITLE
%load_ext rpy2.ipython in Rmagics doesn't work

### ISSUE THREAD

**Issue by drelo** [tiagoantao/bioinf-python#6]
Hi, just a brief question, 

I just installed iphyton 4.0.4 (I installed all under _anaconda_*) but when I try to run the lines in page 17 I can pass further than `%load_ext rpy2.ipython` [I followed the book and the notebook code].  Is there something wrong? Thanks.

>  File "<stdin>", line 1
>     %load_ext rpy2.ipython
>     ^
> SyntaxError: invalid syntax
- using also ubuntu 15.10, the previous steps worked fine. 

I just received the book and I am starting to try to do everything, it is an awesome experience learning this.

**Comment by tiagoantao** [comment]
This is a cell magic for the notebook. I strongly recommend you to install the jupyter notebook available on anaconda. It is really a great experience.

You will also have to install rpy2 (sometimes not trivial - depending on your environment).
