### ISSUE TITLE
wrong test within Welcome notebook

### ISSUE THREAD

**Issue by mrazyho** [tiagoantao/bioinf-python#7]
The test for Python version witihn Welcome.ipynb

```
import platform
major, minor, patch = platform.python_version_tuple()
if major == 3:
```

is wrong, as `platform.python_version_tuple()` returns a tupkle of strings, not integers. The correct test should be

`if major == '3'`

**Comment by tiagoantao** [comment]
Sorry for the delay in answering. You are indeed correct. I changed this accordingly.

Thanks!
