### ISSUE TITLE
Unable to run the 04_PopSim notebooks

### ISSUE THREAD

**Issue by SMartinOSU** [tiagoantao/bioinf-python#8]
Hello,
    I've been trying to learn how to use SimuPop to do some more complex simulations, and was using this book as a guide/example. However, when I went to run the notebooks through Jupyter (using python 3.6.3), I've been getting a variety of errors. I'm not sure if I have something set up incorrectly, as I haven't modified any of the code yet. For example, running 'Complex', in cell 11 (when the simulator should run), I get this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-df95f6569e6b> in calc_demo(gen, pop)
     21 
     22 def calc_demo(gen, pop):
---> 23     if gen > pop.dvars().cut_gen:
     24         add_females = len([ind for ind in pop.individuals([0, 2]) if ind.sex() == 2])
     25     else:

AttributeError: '_dw' object has no attribute 'cut_gen'

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-6b913aec6eac> in <module>()
      1 sim = sp.Simulator(pops, rep=1)
      2 sim.evolve(initOps=init_ops.values(), preOps=pre_ops.values(), postOps=post_ops.values(),
----> 3            matingScheme=mating_scheme, gen=num_gens)

ValueError: Function call failed.

I've been running the cells in order, and I tried going back through and modifying the code by running all the Ops and mating_scheme calls inside the .evolve call, which instead returned this error:

IndexError                                Traceback (most recent call last)
<ipython-input-13-6af2c3dd3987> in calc_demo(gen, pop)
      4     else:
      5         add_females = 0
----> 6     return pop_size + pop.subPopSize([0, 3]) + add_females
      7 
      8 pops = sp.Population(pop_size, loci=[1]*num_loci,

IndexError: population.cpp: 1015 No virtual subpopulation is defined, or subpop index (3) out of range of 0  ~ 18446744073709551615

I apologize if I'm missing something obvious (I'm fairly new to python), and I appreciate any help getting the simulations to run.
-Scott

**Comment by tiagoantao** [comment]
@SMartinOSU Sorry for my delay in answering this. I just had a terrible work week. I will have a look at this tomorrow

**Comment by tiagoantao** [comment]
@SMartinOSU Sorry for my delay in answering this. I just had a terrible work week. I will have a look at this tomorrow

**Comment by tiagoantao** [comment]
I ended up not answering to this. My apologies. The current maintained repo is
https://github.com/PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition
I will address issues there
